export const API_TAGS = {
  USER: "USER",
  BRANCH: "BRANCH",
  BAKERY: "BAKERY",
  DOUGHTROOM: "DOUGHTROOM",
  NOTIFICATION: "NOTIFICATION",
  COMPLAINT: "COMPLAINT",
  NOTFOUND: "NOTFOUND",
  STORAGE: "STORAGE",
  INFORMATION: "INFORMATION",
};
